spring.datasource.url=jdbc:postgresql://localhost:5432/elm
spring.datasource.username=postgres
spring.datasource.password=madinier

spring.datasource.hikari.schema=public

mqb.auth.rounds=12
mqb.auth.secret=scret_536526_xhfurekndfkj_297685_njfreomagb
mqb.auth.issuer=http://localhost:8080
mqb.auth.tokenExpiration=86400