spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

logging.level.root=INFO

auth-api.cors.enabled=false

logging.pattern.console=
myquizzbuilder.logs.file=/var/readresolve.tech/elm/api/logs/myquizzbuilder
logging.file.name=${myquizzbuilder.logs.file}.current.log
logging.logback.rollingpolicy.file-name-pattern=${myquizzbuilder.logs.file}.%d{yyyy-MM-dd}.%i.log.gz
logging.logback.rollingpolicy.max-file-size=10KB
logging.logback.rollingpolicy.total-size-cap=100KB